INSERT INTO animations.t_reservations
(id_reservation, -- serial4 NOT NULL,
 nom, -- varchar(250) NULL,
 prenom, -- varchar(250) NULL,
 tel, -- varchar(100) NULL,
 email, -- varchar(250) NULL,
 commentaire, -- varchar(1000) NULL,
 nb_adultes, -- int4 NOT NULL DEFAULT 0,
 nb_moins_6_ans, -- int4 NOT NULL DEFAULT 0,
 nb_6_8_ans, -- int4 NOT NULL DEFAULT 0,
 nb_9_12_ans, -- int4 NOT NULL DEFAULT 0,
 nb_plus_12_ans, -- int4 NOT NULL DEFAULT 0,
 num_departement, -- varchar(250) NULL,
 id_event, -- int4,
 liste_attente, -- boolean default(null),
 meta_create_date, -- timestamp without time zone DEFAULT now(),
 meta_update_date, -- timestamp without time zone,
 token, -- varchar(50),
 confirmed) -- boolean default(false)
VALUES (1,
        'Dupont',
        'Martin',
        '+33612345678',
        'martin.dupont@example.com',
        'pas de commentaire',
        '2',
        '1',
        '2',
        0,
        0,
        '87',
        1,
        false,
        '2023-06-02 04:05:06',
        '2023-06-07 12:43:20',
        '12345abcde',
        false);